# Generated by Django 4.0.4 on 2022-08-16 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='compania',
            fields=[
                ('nombreCompania', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=60)),
                ('tipoProducto', models.IntegerField()),
                ('cantidadProducto', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='age',
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombreCompania',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
