# Generated by Django 4.0.4 on 2022-08-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_compania_producto_remove_usuario_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='constraseña',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombreProducto',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
