# Generated by Django 4.0.4 on 2022-09-12 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_usuario_apellido_usuario_constraseña_usuario_correo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='compania',
            name='nombreCompania',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombreProducto',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='name',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombreCompania',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventario.compania'),
        ),
    ]
