# Generated by Django 4.0.4 on 2022-09-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_producto_id_remove_usuario_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipoProducto',
            field=models.CharField(max_length=30),
        ),
    ]
