# Generated by Django 4.1 on 2022-09-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InOut_app', '0002_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Empresa',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='Categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='Empresa',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='Cliente',
        ),
        migrations.AlterField(
            model_name='producto',
            name='Imagen',
            field=models.ImageField(default='static/images/pan.png', upload_to=''),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
