# Generated by Django 4.1 on 2022-09-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InOut_app', '0003_remove_usuario_empresa_remove_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='Fecha',
            field=models.DateTimeField(),
        ),
    ]
