# Generated by Django 4.1 on 2022-09-07 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InOut_app', '0004_alter_venta_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='Nombre',
        ),
    ]
