# Generated by Django 4.1 on 2022-09-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InOut_app', '0005_remove_venta_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Imagen',
            field=models.ImageField(default='static/images/pan.png', upload_to='images/'),
        ),
    ]
