# Generated by Django 4.1 on 2022-09-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InOut_app', '0009_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Imagen',
            field=models.ImageField(default='pan.png', upload_to=''),
        ),
    ]
