# Generated by Django 4.1 on 2022-10-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InOut_app', '0011_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestep', models.CharField(max_length=60)),
            ],
        ),
    ]
