# Generated by Django 4.1 on 2022-10-14 03:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('InOut_app', '0012_gop'),
    ]

    operations = [
        migrations.AddField(
            model_name='gop',
            name='Fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
