# Generated by Django 4.1 on 2022-10-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InOut_app', '0013_gop_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='gop',
            name='mes',
            field=models.CharField(default='01', max_length=60),
            preserve_default=False,
        ),
    ]
