# Generated by Django 4.1 on 2022-10-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InOut_app', '0014_gop_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Imagen',
            field=models.ImageField(default='pan.png', upload_to='images/'),
        ),
    ]
