# Generated by Django 4.1 on 2022-11-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InOut_app', '0018_producto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Comp',
            field=models.IntegerField(default=-1),
        ),
    ]
